import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/providers/AppProviders";
import { Inter } from "next/font/google";
import { Snackbar } from "@/components/common/snackbar/Snackbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Adjust weights as needed
  variable: "--font-inter", // Optional: Use a CSS variable
});

export const metadata: Metadata = {
  title: "Create Some Money",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={inter.variable}>
      <body className={``}>
        <Snackbar />
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
